apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-snapshot-test
  namespace: sven
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
