apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: pv-snapshot-test
        persistentVolumeClaim:
          claimName: pv-snapshot-test
      containers:
      - image: quay.io/fedora/mysql-80
        name: mysql-80
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: test
        volumeMounts:
        - name: pv-snapshot-test
          mountPath: /var/lib/mysql
---
